site_name: PyCon KR CoC
theme:
  name: material
  logo: logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep orange
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep orange
      accent: lime

nav:
  # - Home: index.md
  - Code of Conduct (English):
      - Introduction: en/coc/intro.md
      - Enforcement: en/coc/enforcement.md
      - Guidelines: en/coc/guidelines.md
      - Report: en/report.md
  - Code of Conduct (Korean):
      - 의도와 목적: ko/coc/a_intent_and_purpose.md
      - 커뮤니티: ko/coc/b_community.md
      - 의사소통: ko/coc/c_communication.md
      - 프라이버시: ko/coc/d_privacy.md
      - 영리 행위: ko/coc/e_commercial_activity.md
      - 공중 도덕: ko/coc/f_public_morality.md
      - 신고하기: ko/coc/g_reporting.md
      - 기여하기: ko/coc/h_contributing.md
  - REPORT(신고하기): https://forms.gle/M3xNuyMJ9qkGg79m7

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pythonkr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pyconkr
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/pycon_korea

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; <a href="https://github.com/pythonkr" target"_blank" rel="noopener">PyCon KR</a>
